### ISSUE TITLE
Cog Logo missing

### ISSUE THREAD

**Issue by XCompWiz** [KenneyNL/Godot-SplashScreens#4]
Chances are I'm just not looking properly, but I couldn't find the cog logo in the Logos folder. I'd really love to use that one (after verifying it satisfies license requirements and such). 😀

Thank you for all that you do, Kenney!

**Comment by KenneyNL** [comment]
The cog logo isn't available as it isn't a vector file, I'll make sure to include a PNG version of that next update!
