### ISSUE TITLE
Sounds in video

### ISSUE THREAD

**Issue by JekSun97** [KenneyNL/Godot-SplashScreens#5]
Add sound to the video logo, it’s very boring without sound, I can do this if it makes sense, I’ve been a sound engineer for 6 years

**Comment by KenneyNL** [comment]
The video originally contained audio however due to licensing issues it was removed in order to distribute it as CC0. If you wish to create audio, you can do so and share the video yourself o do a pull request with a new video to replace the one without sound.

**Comment by SandSeppel** [comment]
>  I can do this if it makes sense, I’ve been a sound engineer for 6 years

Could you let me know if you are currently planning to do it? If not, I would try it.
